# repo-a: .github/workflows/caller.yml
name: Caller Workflow
on:
  push:
    branches:
      - main

jobs:
  call_external_workflow:
    uses: chenchugokuljangam13/repo-b/.github/workflows/reusable.yml@main
    with:
      username: "alice"
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}